import Head from "next/head";
import { Inter } from "next/font/google";
import { Container } from "@/components/Container";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Fave Chess Openings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container as="main" className={inter.className}>
        <Container
          as="header"
          css={{
            background: "black",
            color: "white",
            padding: 16,
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
          }}
        >
          <h1>Fave Chess Openings</h1>
          <p>About</p>
        </Container>
      </Container>
    </>
  );
}
